---
server: localhost:7687 # server location, defaults to localhost and standard neo4j port
database: geno # developed with a "geno" database in neo4j Community Edition
user: geno # neo4j user authorized to access the database
constraints:
    # Example of constraints for a database
    # -------------------------------------
    # DatabaseName
    #     Constraint Type:
    #         - Label: Node Label
    #           Properties: $ !important: note no dash here
    #             - Property 1 required for uniqueness of exmaple node label
    #             - Property 2 required for uniqueness of exmaple node label
    #             - ... as many as required
    #     NodePropertyExistence:
    #         - Label:
    #           Properties:
    #     RelationshipUniqueness:
    #         - Label:
    #           Properties:
    #     RelationshipKeys:
    #         - Label:
    #           Properties:
    #     RelationshipPropertyExistence:
    #         - Label:
    #           Properties:
    geno:
        NodeUniqueness:
            - Label: NodeTypeA
              Properties:
                  - Prop1
            - Label: NodeTypeB
              Properties:
                  - Prop1
                  - Prop2
        NodeKeys:
            - TypeC:
                  - Prop1
                  - Prop2
            - TypeD:
                  - Prop3
                  - Prop4
        NodePropertyExistence:
        RelationshipUniqueness:
        RelationshipKeys:
        RelationshipPropertyExistence:
